FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive \
    TERM=xterm-256color

RUN apt-get update && apt-get install -y \
    zsh \
    wget \
    git \
    git-lfs \
    git-sizer \
    curl \
    byobu \
    htop \
    plocate \
    fonts-powerline \
    fontconfig \
    iputils-ping \
    nano \
    vim \
    net-tools \
    tldr \
    zip \
    unzip \
    tree \
    procps \
    nvtop \
    build-essential \
    libssl-dev \
    poppler-utils \
    python3 \
    python3-pip \
    python3-dev \
    python3-venv \
    openjdk-11-jdk \
    postgresql \
    postgresql-contrib 

RUN apt-get install -y \
    ninja-build \
    gcc \
    g++ \
    gdb \
    sqlite3 \
    libsqlite3-dev \
    cmake

RUN apt-get install -y nvidia-cuda-toolkit

RUN apt-get install -y apt-transport-https \
    ca-certificates \
    software-properties-common \
    lsb-release \
    gnupg \
    jq

RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-chrome-keyring.gpg

RUN echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list

RUN apt-get update && apt-get install -y --no-install-recommends \
    google-chrome-stable \
    libglib2.0-0 \
    libnss3 \
    libfontconfig1

RUN CHROMEDRIVER_URL=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform=="linux64") | .url') && \
    echo "Downloading ChromeDriver from: $CHROMEDRIVER_URL" && \
    wget -q --show-progress -O /tmp/chromedriver.zip "$CHROMEDRIVER_URL" && \
    unzip -qq /tmp/chromedriver.zip -d /tmp/ && \
    mv /tmp/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver && \
    chmod +x /usr/local/bin/chromedriver && \
    rm /tmp/chromedriver.zip && \
    rm -rf /tmp/chromedriver-linux64 && \
    chromedriver --version

# Set up virtual environment
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Install Oh My Zsh and themes
# p10k configure
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
COPY fonts/ /usr/share/fonts/
RUN fc-cache -fv
RUN git clone --depth=1 --recurse-submodules https://github.com/romkatv/powerlevel10k.git /powerlevel10k
RUN GITSTATUS_CACHE_DIR=/powerlevel10k/gitstatus/usrbin /powerlevel10k/gitstatus/install -f -s linux -m x86_64
RUN git -C /powerlevel10k submodule update --init --recursive --force
# RUN git -C /powerlevel10k pull /powerlevel10k/gitstatus/install -f
RUN echo 'source /powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc \
    && sed -i.bak '/^ZSH_THEME=/d' ~/.zshrc \
    && chsh -s $(which zsh)

SHELL ["/usr/bin/zsh", "-c"]

# Clone the Zsh plugins
RUN git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.zsh/zsh-autosuggestions && \
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.zsh/zsh-syntax-highlighting && \
    git clone https://github.com/agkozak/zsh-z.git ~/.zsh/zsh-z && \
    git clone https://github.com/zsh-users/zsh-completions.git ~/.zsh/zsh-completions

# Add the plugin's source to .zshrc
RUN echo "source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh" >> ~/.zshrc && \
    echo "source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> ~/.zshrc && \
    echo "source ~/.zsh/zsh-z/zsh-z.plugin.zsh" >> ~/.zshrc && \
    echo "fpath+=(~/.zsh/zsh-completions/src)" >> ~/.zshrc && \
    echo "autoload -U compinit && compinit" >> ~/.zshrc

# Install Node (Bug to fix: for the moment it takes many resources when launching the container)
# ENV NVM_DIR=/root/.nvm

# RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash \
#     && bash -c "source $NVM_DIR/nvm.sh && nvm install 20 && nvm alias default 20"

# ENV PATH=$NVM_DIR/versions/node/v20.*/bin:$PATH
# RUN bash -c "source $NVM_DIR/nvm.sh && node -v && npm -v"

# Install Miniforge
RUN wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -O /tmp/miniforge.sh \
    && /bin/bash /tmp/miniforge.sh -b -p /opt/miniforge \
    && rm /tmp/miniforge.sh
ENV PATH="/opt/miniforge/bin:$PATH"
RUN conda init zsh
RUN zsh -l

# Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Install Scala
RUN wget https://downloads.lightbend.com/scala/2.13.15/scala-2.13.15.deb && \
    dpkg -i scala-2.13.15.deb && \
    apt-get install -f && \
    rm scala-2.13.15.deb

# Set Scala and Java paths
ENV SCALA_HOME=/usr/share/scala
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH=$PATH:$JAVA_HOME/bin:$SCALA_HOME/bin

# Install Spark
ENV SPARK_VERSION=3.5.5
ENV HADOOP_VERSION=3
ENV SPARK_HOME=/opt/spark
ENV PATH=$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin

RUN wget -qO- "https://dlcdn.apache.org/spark/spark-$SPARK_VERSION/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz" | tar -xz -C /opt/ \
    && mv /opt/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION $SPARK_HOME

# Install Node.js directly from NodeSource
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && npm --version \
    && node --version

# # Configure Spark
# COPY spark-defaults.conf $SPARK_HOME/conf/spark-defaults.conf
# COPY log4j.properties $SPARK_HOME/conf/log4j.properties


# Install Docker
RUN apt-get install -y apt-transport-https ca-certificates software-properties-common lsb-release gnupg
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
RUN apt-get update && apt-get install -y docker-ce docker-ce-cli containerd.io

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Expose Docker socket
# This allows the container to communicate with the host's Docker daemon.
# Note: This will be mounted when running the container using the `-v /var/run/docker.sock:/var/run/docker.sock` flag.
VOLUME ["/var/run/docker.sock"]

# Install Code Server
RUN curl -fsSL https://code-server.dev/install.sh | sh

ADD settings.json /root/.local/share/code-server/User/settings.json
ADD launch.json /root/.local/share/code-server/User/launch.json
ADD tasks.json /root/.local/share/code-server/User/tasks.json
WORKDIR /workspace

COPY extensions /extensions
RUN code-server --install-extension /extensions/mathematic.vscode-pdf-0.0.6.vsix
RUN code-server --install-extension eamodio.gitlens
RUN code-server --install-extension ms-python.python
RUN code-server --install-extension ms-toolsai.jupyter
RUN code-server --install-extension charliermarsh.ruff
RUN code-server --install-extension njpwerner.autodocstring
RUN code-server --install-extension streetsidesoftware.code-spell-checker
RUN code-server --install-extension esbenp.prettier-vscode
RUN code-server --install-extension mechatroner.rainbow-csv
RUN code-server --install-extension ms-azuretools.vscode-docker
RUN code-server --install-extension zhuangtongfa.Material-theme
RUN code-server --install-extension PKief.material-icon-theme
RUN code-server --install-extension pomdtr.excalidraw-editor
RUN code-server --install-extension ms-python.debugpy
RUN code-server --install-extension Continue.continue
RUN code-server --install-extension GitHub.github-vscode-theme
RUN code-server --install-extension mhutchie.git-graph
RUN code-server --install-extension GrapeCity.gc-excelviewer
RUN code-server --install-extension Vue.volar

RUN wget https://github.com/microsoft/vscode-cpptools/releases/download/v1.24.5/cpptools-linux-x64.vsix
RUN code-server --install-extension cpptools-linux-x64.vsix

# Adding your user to the Docker group (Optional, depends on your use case)
RUN usermod -aG docker root

# Expose Spark UI port (master and worker) and Code server
EXPOSE 8080 8081 40000

# Command to run Code Server
CMD ["code-server", "--bind-addr", "0.0.0.0:40000", "--auth", "none"]
