# RTX TUF 3090
# Ubuntu 22.04
# Driver 515

# Does not work 
# FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-devel

# Work
# FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-devel
# FROM pytorch/pytorch:1.13.0-cuda11.6-cudnn8-devel


# Current
FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-devel

CMD ["/bin/sh"]
